# Generated by Django 4.0.2 on 2022-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='format:required, letters, numbers, anderscores or hyphens', max_length=255, verbose_name='category safe url'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(help_text='format:required, unique', max_length=50, unique=True, verbose_name='product website ID')),
                ('slug', models.SlugField(help_text='format:required, letters, numbers, anderscores or hyphens', max_length=255, verbose_name='product safe url')),
                ('name', models.CharField(blank=True, help_text='format: required, max-255', max_length=255, verbose_name='product name')),
                ('description', models.TextField(blank=True, help_text='format: required', verbose_name='product description')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=product visible', verbose_name='product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date product created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date product updated')),
                ('category', models.ManyToManyField(to='inventory.Category')),
            ],
        ),
    ]
