# Generated by Django 4.0.2 on 2022-05-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format:required, unique, max-255', max_length=255, unique=True, verbose_name='peoduct atribute name')),
                ('description', models.CharField(help_text='format:required', max_length=255, verbose_name='peoduct atribute description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribut_value', models.CharField(help_text='format:required, unique, max-255', max_length=255, verbose_name='atribute value')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_atribute', to='inventory.productattribut')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(blank=True, default=0, help_text='format: Y-m-d H:M:S, null=true, blank=true', null=True, verbose_name='inventory stock check date')),
                ('units', models.IntegerField(default=0, help_text='format: required, default=1', verbose_name='units/qty of stock')),
                ('units_solid', models.IntegerField(default=0, help_text='format: required, default=1', verbose_name='units/qty of stock')),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_product', to='inventory.productinventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributevalues', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_atribute_value', to='inventory.productattributvalue')),
                ('productinventry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='inventory.productinventory')),
            ],
            options={
                'unique_together': {('attributevalues', 'productinventry')},
            },
        ),
        migrations.AddField(
            model_name='productinventory',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_attribute_values', through='inventory.ProductAttributValues', to='inventory.ProductAttributValue'),
        ),
    ]
